[package]
name = "snakers"
version = "0.1.0"
authors = ["Fatpandac <i@fatpandac.com>"]
license = "MIT"
edition = "2021"

[dependencies]
rand = "0.8.4"
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
